name = "uptime-monitor"
main = "src/index.js"
compatibility_date = "2024-04-07"

[[d1_databases]]
binding = "DB"
database_name = "uptime-monitor"
database_id = "a7036eaf-d6e8-4855-81a4-c3405f295cb6"

[triggers]
crons = ["*/15 * * * *"]

[vars]
ADMIN_PASSWORD = "WQGnuAcbIByj"
